"""
M1 Code Generation Worker for APPLUS3.
GENERATED BY MULTI-IA CONSENSUS (GPT-4o + Claude + DeepSeek)
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

from orchestrator.knowledge_graph import KnowledgeGraph, Node, NodeType
from orchestrator.retrieval import ContextRetriever, RetrievalResult


@dataclass
class GenerationResult:
    """Result of code generation for a specific node."""
    node_id: str
    generated_code: str
    context_used: Optional[str]


class M1Worker:
    """APPLUS3 code generation worker for M1 stage."""

    def __init__(self, kg: KnowledgeGraph, retriever: ContextRetriever) -> None:
        """
        Initialize M1 worker with knowledge graph and context retriever.

        Args:
            kg: KnowledgeGraph instance containing node information
            retriever: ContextRetriever for fetching relevant context
        """
        self.kg = kg
        self.retriever = retriever

    def generate_code(self, node_id: str) -> GenerationResult:
        """
        Generate code for a specific node using its context.

        Args:
            node_id: ID of the node to generate code for

        Returns:
            GenerationResult containing generated code and context used
        """
        # Retrieve relevant context for the node
        context = self.retriever.get_context_for_node(node_id)

        # Get the node from knowledge graph
        node = self.kg.get_node(node_id)
        if not node:
            return GenerationResult(
                node_id=node_id,
                generated_code="# Error: Node not found",
                context_used=None
            )

        # Generate code based on node type and context
        generated_code = self._generate_code_for_node(node, context)
        context_text = self.retriever.build_prompt_context(context)

        return GenerationResult(
            node_id=node_id,
            generated_code=generated_code,
            context_used=context_text
        )

    def _generate_code_for_node(self, node: Node, context: RetrievalResult) -> str:
        """
        Internal method to generate code based on node type.

        Args:
            node: Node to generate code for
            context: Retrieved context for the node

        Returns:
            Generated code as string
        """
        if node.node_type == NodeType.FUNCTION:
            return self._generate_function_code(node, context)
        elif node.node_type == NodeType.CLASS:
            return self._generate_class_code(node, context)
        elif node.node_type == NodeType.MODULE:
            return self._generate_module_code(node, context)
        else:
            return self._generate_generic_code(node, context)

    def _generate_function_code(self, node: Node, context: RetrievalResult) -> str:
        """Generate code for function nodes."""
        func_name = node.metadata.get("name", "function_name")
        return f'''def {func_name}():
    """Generated function for {node.id}."""
    # Context relevance: {context.relevance:.2f}
    pass
'''

    def _generate_class_code(self, node: Node, context: RetrievalResult) -> str:
        """Generate code for class nodes."""
        class_name = node.metadata.get("name", "ClassName")
        return f'''class {class_name}:
    """Generated class for {node.id}."""

    def __init__(self):
        # Context relevance: {context.relevance:.2f}
        pass
'''

    def _generate_module_code(self, node: Node, context: RetrievalResult) -> str:
        """Generate code for module nodes."""
        module_name = node.metadata.get("name", "module")
        return f'''"""
Module: {module_name}
Generated for node {node.id}
Context relevance: {context.relevance:.2f}
"""

# Module implementation
'''

    def _generate_generic_code(self, node: Node, context: RetrievalResult) -> str:
        """Generate code for generic node types."""
        return f'''# Code for node: {node.id}
# Type: {node.node_type.value}
# Content: {node.content[:100]}...
# Context relevance: {context.relevance:.2f}
'''
