"""
M0 Analysis Worker for APPLUS3.
GENERATED BY MULTI-IA CONSENSUS (GPT-4o + Claude + DeepSeek)
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import List, Dict, Any
import re
import uuid

from knowledge_graph import KnowledgeGraph, Node, NodeType


@dataclass
class AnalysisResult:
    """Result of M0 analysis phase."""
    node_ids: List[str]
    components: Dict[str, Any]
    summary: str


class M0Worker:
    """Initial analysis worker for APPLUS3 system."""

    def __init__(self, kg: KnowledgeGraph) -> None:
        """
        Initialize M0 worker with knowledge graph.

        Args:
            kg: KnowledgeGraph instance for node storage
        """
        self.kg = kg
        self.analysis_count = 0

    def analyze_idea(self, idea: str) -> AnalysisResult:
        """
        Main analysis pipeline for raw ideas.

        Args:
            idea: Raw idea text to analyze

        Returns:
            AnalysisResult containing extracted components and created nodes
        """
        self.analysis_count += 1

        components = self.extract_components(idea)
        node_ids = self.create_nodes(components)
        summary = self._generate_summary(components, node_ids)

        return AnalysisResult(
            node_ids=node_ids,
            components=components,
            summary=summary
        )

    def extract_components(self, idea: str) -> Dict[str, Any]:
        """
        Extract structured components from raw idea text.

        Args:
            idea: Raw idea text

        Returns:
            Dictionary containing extracted components
        """
        return {
            "entities": self._extract_entities(idea),
            "concepts": self._extract_concepts(idea),
            "actions": self._extract_actions(idea),
            "domain_hints": self._extract_domain_hints(idea)
        }

    def create_nodes(self, components: Dict[str, Any]) -> List[str]:
        """
        Create initial nodes in knowledge graph from extracted components.

        Args:
            components: Extracted components dictionary

        Returns:
            List of created node IDs
        """
        node_ids = []

        # Create entity nodes
        for entity in components.get("entities", []):
            node_id = str(uuid.uuid4())
            node = Node(
                id=node_id,
                node_type=NodeType.CLASS,
                content=entity,
                metadata={"source": "m0_extraction", "category": "entity"}
            )
            self.kg.add_node(node)
            node_ids.append(node_id)

        # Create concept nodes
        for concept in components.get("concepts", []):
            node_id = str(uuid.uuid4())
            node = Node(
                id=node_id,
                node_type=NodeType.PATTERN,
                content=concept,
                metadata={"source": "m0_extraction", "category": "concept"}
            )
            self.kg.add_node(node)
            node_ids.append(node_id)

        # Create action nodes
        for action in components.get("actions", []):
            node_id = str(uuid.uuid4())
            node = Node(
                id=node_id,
                node_type=NodeType.FUNCTION,
                content=action,
                metadata={"source": "m0_extraction", "category": "action"}
            )
            self.kg.add_node(node)
            node_ids.append(node_id)

        return node_ids

    def _extract_entities(self, idea: str) -> List[str]:
        """Extract entities from idea (capitalized words)."""
        entities = re.findall(r'\b[A-Z][a-z]+\b', idea)
        return list(set(entities))

    def _extract_concepts(self, idea: str) -> List[str]:
        """Extract conceptual terms from idea text."""
        concept_keywords = ["system", "process", "method", "approach", "framework", "service", "module"]
        concepts = []
        for keyword in concept_keywords:
            if keyword.lower() in idea.lower():
                concepts.append(keyword)
        return concepts

    def _extract_actions(self, idea: str) -> List[str]:
        """Extract action verbs from idea text."""
        action_pattern = r'\b(create|develop|implement|analyze|process|generate|build|design|manage|handle)\w*\b'
        actions = re.findall(action_pattern, idea.lower())
        return list(set(actions))

    def _extract_domain_hints(self, idea: str) -> List[str]:
        """Extract domain hints from idea."""
        domains = {"api", "database", "web", "mobile", "cloud", "ai", "ml", "data", "auth", "user"}
        idea_lower = idea.lower()
        return [d for d in domains if d in idea_lower]

    def _generate_summary(self, components: Dict[str, Any], node_ids: List[str]) -> str:
        """Generate analysis summary."""
        entity_count = len(components.get("entities", []))
        concept_count = len(components.get("concepts", []))
        action_count = len(components.get("actions", []))

        return (
            f"M0 Analysis #{self.analysis_count}: Extracted {entity_count} entities, "
            f"{concept_count} concepts, {action_count} actions. "
            f"Created {len(node_ids)} nodes."
        )
