"""
APPLUS3 Desktop Application.
GENERATED BY MULTI-IA CONSENSUS (GPT-4o + Claude + DeepSeek)
via APPLUS-WEBAPP M0→M1 Pipeline
"""

import tkinter as tk
from tkinter import ttk, messagebox, filedialog, scrolledtext
import requests
import threading
import json
import sys
import os

# Add _internal folder to path
if getattr(sys, 'frozen', False):
    application_path = sys._MEIPASS
else:
    application_path = os.path.dirname(os.path.abspath(__file__))

_internal_path = os.path.join(application_path, '_internal')
if os.path.exists(_internal_path):
    sys.path.insert(0, _internal_path)

# Try to import local Knowledge Graph
try:
    from orchestrator.knowledge_graph import KnowledgeGraph, Node, NodeType
    HAS_KG = True
except ImportError:
    HAS_KG = False


class APPLUS3DesktopApp:
    def __init__(self, root):
        self.root = root
        self.root.title("APPLUS3 Desktop")
        self.root.geometry("800x600")
        self.root.minsize(600, 400)
        self.root.configure(bg="#2e2e2e")

        # Configure dark theme
        self.setup_dark_theme()

        # Initialize Knowledge Graph if available
        self.kg = KnowledgeGraph() if HAS_KG else None

        # Initialize UI components
        self.setup_menu()
        self.setup_widgets()
        self.setup_status_bar()

        # Placeholder functionality
        self.setup_placeholder()

        # API endpoint
        self.api_url = "https://applus-webapp-backend.onrender.com/api/ai/test-consensus"

        # Projects directory
        self.projects_dir = os.path.join(os.environ.get('APPDATA', '.'), 'APPLUS3', 'projects')
        os.makedirs(self.projects_dir, exist_ok=True)

    def setup_dark_theme(self):
        style = ttk.Style()
        style.theme_use('clam')
        style.configure('TFrame', background='#2e2e2e')
        style.configure('TLabel', background='#2e2e2e', foreground='white')
        style.configure('TButton', background='#444444', foreground='white')
        style.map('TButton', background=[('active', '#505050')])
        style.configure('TEntry', fieldbackground='#444444', foreground='white', borderwidth=0)

    def setup_menu(self):
        menubar = tk.Menu(self.root, bg="#444444", fg="white", activebackground="#505050", activeforeground="white")
        self.root.config(menu=menubar)

        file_menu = tk.Menu(menubar, tearoff=0, bg="#444444", fg="white", activebackground="#505050", activeforeground="white")
        menubar.add_cascade(label="File", menu=file_menu)
        file_menu.add_command(label="Save Project", command=self.save_project)
        file_menu.add_command(label="Load Project", command=self.load_project)
        file_menu.add_separator()
        file_menu.add_command(label="Exit", command=self.root.quit)

        # Help menu
        help_menu = tk.Menu(menubar, tearoff=0, bg="#444444", fg="white")
        menubar.add_cascade(label="Help", menu=help_menu)
        help_menu.add_command(label="About", command=self.show_about)

    def setup_widgets(self):
        # Main frame
        main_frame = ttk.Frame(self.root)
        main_frame.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

        # Title
        title_label = tk.Label(main_frame, text="APPLUS3 Multi-IA Code Generator",
                              font=("Segoe UI", 14, "bold"), bg="#2e2e2e", fg="white")
        title_label.pack(pady=(0, 10))

        # KG Status
        kg_status = "Knowledge Graph: Active" if HAS_KG else "Knowledge Graph: Not available"
        kg_label = tk.Label(main_frame, text=kg_status, font=("Segoe UI", 9),
                           bg="#2e2e2e", fg="#00ff00" if HAS_KG else "#ff6666")
        kg_label.pack()

        # Entry for idea input
        input_label = ttk.Label(main_frame, text="Enter your idea:")
        input_label.pack(anchor='w', pady=(10, 5))

        self.entry_var = tk.StringVar()
        self.entry = tk.Entry(main_frame, textvariable=self.entry_var, width=80,
                             bg="#444444", fg="white", insertbackground="white",
                             font=("Segoe UI", 11), relief=tk.FLAT, bd=5)
        self.entry.pack(fill=tk.X, pady=(0, 10), ipady=8)

        # Generate button
        self.generate_button = tk.Button(main_frame, text="Generate", command=self.generate_idea,
                                        bg="#0d6efd", fg="white", font=("Segoe UI", 10, "bold"),
                                        relief=tk.FLAT, padx=20, pady=8, cursor="hand2")
        self.generate_button.pack(pady=(0, 15))
        self.generate_button.bind("<Enter>", lambda e: self.generate_button.config(bg="#0b5ed7"))
        self.generate_button.bind("<Leave>", lambda e: self.generate_button.config(bg="#0d6efd"))

        # Results label
        results_label = ttk.Label(main_frame, text="Results:")
        results_label.pack(anchor='w', pady=(0, 5))

        # Scrollable text area for results
        self.result_text = scrolledtext.ScrolledText(main_frame, wrap='word', height=15,
                                                     bg='#444444', fg='white',
                                                     font=("Consolas", 10),
                                                     insertbackground="white")
        self.result_text.pack(fill='both', expand=True)

    def setup_status_bar(self):
        self.status_var = tk.StringVar(value="Ready")
        self.status_bar = tk.Label(self.root, textvariable=self.status_var,
                                  relief='sunken', anchor='w',
                                  bg="#444444", fg="white", padx=10)
        self.status_bar.pack(side='bottom', fill='x')

    def setup_placeholder(self):
        self.placeholder_text = "Enter your idea here... (e.g., 'Create a REST API for user management')"
        self.entry.insert(0, self.placeholder_text)
        self.entry.config(fg="#888888")
        self.entry.bind("<FocusIn>", self.clear_placeholder)
        self.entry.bind("<FocusOut>", self.add_placeholder)

    def clear_placeholder(self, event):
        if self.entry_var.get() == self.placeholder_text:
            self.entry_var.set('')
            self.entry.config(fg="white")

    def add_placeholder(self, event):
        if not self.entry_var.get():
            self.entry_var.set(self.placeholder_text)
            self.entry.config(fg="#888888")

    def generate_idea(self):
        idea = self.entry_var.get().strip()
        if not idea or idea == self.placeholder_text:
            messagebox.showwarning("Input Error", "Please enter an idea before generating.")
            return

        self.status_var.set("Connecting to Multi-IA...")
        self.generate_button.config(state=tk.DISABLED, text="Generating...")
        self.result_text.delete('1.0', tk.END)
        self.result_text.insert('end', "Sending request to APPLUS-WEBAPP Multi-IA...\n\n")

        threading.Thread(target=self.call_api, args=(idea,), daemon=True).start()

    def call_api(self, idea):
        try:
            self.root.after(0, lambda: self.status_var.set("Waiting for Multi-IA response..."))

            payload = {"prompt": idea}
            response = requests.post(self.api_url, json=payload, timeout=120)
            response.raise_for_status()
            result = response.json()

            # Store in Knowledge Graph if available
            if self.kg and HAS_KG:
                try:
                    node = Node(
                        id=f"idea_{hash(idea) % 10000}",
                        node_type=NodeType.MODULE,
                        content=idea,
                        metadata={"consensus": result.get("consensus_result", "unknown")}
                    )
                    self.kg.add_node(node)
                except Exception:
                    pass

            self.root.after(0, lambda: self.display_results(result))

        except requests.exceptions.Timeout:
            self.root.after(0, lambda: messagebox.showerror("Error", "Request timed out. The server may be starting up. Please try again."))
        except requests.exceptions.ConnectionError:
            self.root.after(0, lambda: messagebox.showerror("Error", "Connection error. Please check your internet connection."))
        except requests.exceptions.RequestException as e:
            self.root.after(0, lambda: messagebox.showerror("API Error", f"An error occurred: {e}"))
        except Exception as e:
            self.root.after(0, lambda: messagebox.showerror("Error", f"Unexpected error: {e}"))
        finally:
            self.root.after(0, self.reset_button)

    def display_results(self, result):
        self.result_text.delete('1.0', tk.END)

        consensus = result.get("consensus_result", "Unknown")
        self.result_text.insert('end', f"=== CONSENSUS: {consensus} ===\n\n")

        if "majority_response" in result:
            self.result_text.insert('end', "--- Generated Code ---\n")
            code = result["majority_response"]
            # Remove markdown code blocks if present
            if code.startswith("```"):
                code = code.split("\n", 1)[1] if "\n" in code else code[3:]
            if code.endswith("```"):
                code = code[:-3]
            self.result_text.insert('end', code.strip())
            self.result_text.insert('end', "\n\n")

        if "individual_responses" in result:
            self.result_text.insert('end', f"\n--- Individual Models ({len(result['individual_responses'])}) ---\n")
            for resp in result["individual_responses"]:
                model = resp.get("model", "unknown")
                confidence = resp.get("confidence", 0)
                self.result_text.insert('end', f"  {model}: confidence={confidence}\n")

        if "total_cost" in result:
            self.result_text.insert('end', f"\nTotal Cost: ${result['total_cost']:.4f}")

        self.status_var.set(f"Ready - Consensus: {consensus}")

    def reset_button(self):
        self.generate_button.config(state=tk.NORMAL, text="Generate")

    def save_project(self):
        file_path = filedialog.asksaveasfilename(
            initialdir=self.projects_dir,
            defaultextension=".json",
            filetypes=[("JSON files", "*.json"), ("Text files", "*.txt"), ("All files", "*.*")]
        )
        if file_path:
            try:
                project_data = {
                    "idea": self.entry_var.get(),
                    "result": self.result_text.get('1.0', tk.END)
                }
                with open(file_path, 'w', encoding='utf-8') as file:
                    json.dump(project_data, file, indent=2)
                self.status_var.set(f"Project saved: {os.path.basename(file_path)}")
            except Exception as e:
                messagebox.showerror("Save Error", f"Could not save file: {e}")

    def load_project(self):
        file_path = filedialog.askopenfilename(
            initialdir=self.projects_dir,
            filetypes=[("JSON files", "*.json"), ("All files", "*.*")]
        )
        if file_path:
            try:
                with open(file_path, 'r', encoding='utf-8') as file:
                    project_data = json.load(file)
                self.entry_var.set(project_data.get("idea", ""))
                self.entry.config(fg="white")
                self.result_text.delete('1.0', tk.END)
                self.result_text.insert('end', project_data.get("result", ""))
                self.status_var.set(f"Project loaded: {os.path.basename(file_path)}")
            except Exception as e:
                messagebox.showerror("Load Error", f"Could not load file: {e}")

    def show_about(self):
        messagebox.showinfo("About APPLUS3 Desktop",
            "APPLUS3 Desktop Application\n"
            "Version 1.0.0\n\n"
            "Multi-IA Code Generation with Knowledge Graph\n"
            "GPT-4o + Claude + DeepSeek\n\n"
            "Generated by APPLUS-WEBAPP M0→M1 Pipeline")


if __name__ == "__main__":
    root = tk.Tk()
    app = APPLUS3DesktopApp(root)
    root.mainloop()
