@echo off
REM APPLUS3 Build Script
REM GENERATED BY MULTI-IA CONSENSUS (GPT-4o + Claude + DeepSeek)

echo ========================================
echo APPLUS3 Desktop Build Script
echo ========================================
echo.

:: Check if Python is installed
echo Checking Python installation...
python --version >nul 2>&1
if errorlevel 1 (
    echo Error: Python is not installed or not in PATH
    echo Please install Python from https://www.python.org/
    pause
    exit /b 1
)

:: Install required packages
echo Installing required packages...
pip install pyinstaller requests >nul 2>&1
if errorlevel 1 (
    echo Error: Failed to install required packages.
    pause
    exit /b 1
)

:: Run PyInstaller
echo Building executable with PyInstaller...
pyinstaller --onefile --windowed --name APPLUS3 --add-data "_internal;_internal" --icon=icon.ico applus3_desktop.py 2>nul || pyinstaller --onefile --windowed --name APPLUS3 --add-data "_internal;_internal" applus3_desktop.py

if errorlevel 1 (
    echo Error: PyInstaller build failed.
    pause
    exit /b 1
)

echo.
echo ========================================
echo BUILD SUCCESSFUL!
echo Executable created: dist\APPLUS3.exe
echo ========================================
pause
