; APPLUS3 Installer Script for Inno Setup
; GENERATED BY MULTI-IA CONSENSUS (GPT-4o + Claude + DeepSeek)

[Setup]
AppName=APPLUS3
AppVersion=1.0.0
AppPublisher=APPLUS
AppPublisherURL=https://github.com/Josrrito/applus3
DefaultDirName={autopf}\APPLUS3
DefaultGroupName=APPLUS3
UninstallDisplayIcon={app}\APPLUS3.exe
OutputDir=Output
OutputBaseFilename=APPLUS3-Setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\APPLUS3.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\APPLUS3"; Filename: "{app}\APPLUS3.exe"
Name: "{group}\{cm:UninstallProgram,APPLUS3}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\APPLUS3"; Filename: "{app}\APPLUS3.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\APPLUS3.exe"; Description: "{cm:LaunchProgram,APPLUS3}"; Flags: nowait postinstall skipifsilent
